### ISSUE TITLE
Cannot import v2 into project using modules

### ISSUE THREAD

**Issue by CodyDWJones** [ZachtimusPrime/Go-Splunk-HTTP#17]
The latest release tag cannot be used:

```
$ mkdir repro
$ cd repro
$ go mod init github.com/CodyDWJones/repro
$ go get github.com/ZachtimusPrime/Go-Splunk-HTTP/v2
go get github.com/ZachtimusPrime/Go-Splunk-HTTP/v2: module github.com/ZachtimusPrime/Go-Splunk-HTTP@upgrade found (v0.0.0-20201008172325-b298e35fa174), but does not contain package github.com/ZachtimusPrime/Go-Splunk-HTTP/v2
```

The following fails too but that's expected since v2 is considered to contain breaking changes:
```
$ go get github.com/ZachtimusPrime/Go-Splunk-HTTP@v2.0.0
go get github.com/ZachtimusPrime/Go-Splunk-HTTP@v2.0.0: github.com/ZachtimusPrime/Go-Splunk-HTTP@v2.0.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

**Comment by ZachtimusPrime** [comment]
That second error makes it sounds like your module can't have a major version higher than that of golang by only mentioning v0 and v1. It doesn't help that I've been out of golang since before modules were introduced...

**Comment by antoineco** [comment]
Unfortunately "v2 and above" has to be treated differently with Go modules, and it's really annoying:

> In semantic versioning, changing the major version number indicates a lack of backwards compatibility with earlier versions. To preserve import compatibility, the go command requires that modules with major version v2 or later use a module path with that major version as the final element
>
> -- https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning

**Comment by ZachtimusPrime** [comment]
Deleting release v2.0.0 wouldn't create an issue would it? @antoineco

**Comment by antoineco** [comment]
@ZachtimusPrime no, go ahead 👍 It's not compatible with modules anyway.

There is an important detail to consider though. The `go.mod` file is in the **sub-module** `splunk/`, so you need to create a tag called `splunk/v2.0.1` for `go get` to work as expected, not `v2.0.1`.

```console
$ go get github.com/ZachtimusPrime/Go-Splunk-HTTP/splunk/v2@v2.0.1
go get github.com/ZachtimusPrime/Go-Splunk-HTTP/splunk/v2@v2.0.1: github.com/ZachtimusPrime/Go-Splunk-HTTP/splunk/v2@v2.0.1: invalid version: unknown revision splunk/v2.0.1
```

You can do that without affecting the release you just created:
```
git tag splunk/v2.0.1
git push --tags
git tag --delete v2.0.1
git push -d origin v2.0.1
```

**Comment by ZachtimusPrime** [comment]
@antoineco Would moving the `go.mod` file into root work as well? To prevent having to remember to push a new `splunk/vX.X.X` tag with each release.

In the meantime, the tags have been updated.

**Comment by antoineco** [comment]
@ZachtimusPrime sweet, it looks good now on my side, thanks a lot!

You could move `./splunk/v2` to `./v2` and it would do what you expect, yes. If you do that, don't forget to update `go.mod` to reflect the change of path as well.

**Comment by ZachtimusPrime** [comment]
Cool, I'll likely wait till the next time something needs to be merged in and tack that on so that specific tags don't need to be created each time.

Thank you both for the additions!
